version: '3.7'
services:
  app:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && sleep 30;bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 4000 -b 0.0.0.0"
    ports:
      - 4000:4000
    volumes:
      - ./:/rails_tuning_sample_app
      - ~/.bashrc:/root/.bashrc
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - .devcontainer/.vimrc:/root/.vimrc
    working_dir: /rails_tuning_sample_app
    tty: true
    stdin_open: true
